#!/usr/bin/env bash
# Reads /etc/passwd and displays specific user details

while IFS=":" read -r user password uid gid info home shell
do
    echo "The user $user has an ID of $uid and a home directory of $home"
done < /etc/passwd
