#!/usr/bin/env bash
# Parses an Apache log file and displays number of occurrences per IP and HTTP status code

awk '
{
    ip = $1
    status = $9
    if (status ~ /^[0-9]+$/)
        count[ip, status]++
}
END {
    for (key in count) {
        split(key, parts, SUBSEP)
        print count[key], parts[1], parts[2]
    }
}
' | sort -nr

