#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code from apache-access.log
awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -k1,1rn -k2,2 -k3,3 | awk '{print $1, $2, $3}'
